name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25.3-1]

    steps:
    - uses: actions/checkout@v2
    - name: Install packagess
      run: |
        curl "https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_${{ matrix.otp }}~ubuntu~bionic_amd64.deb" > erlang.deb
        sudo apt-get update
        sudo apt-get install ./erlang.deb
        sudo apt-get install -y asciidoctor libxml2-utils
        wget https://s3.amazonaws.com/rebar3/rebar3
        chmod +x ./rebar3
        ./rebar3 local install

    - name: Compile and run tests
      run: |
        export PATH="/home/runner/.cache/rebar3/bin:$PATH"
        make
